### ISSUE TITLE
Add wheels for Python3.9

### ISSUE THREAD

**Issue by scaramallion** [pydicom/pylibjpeg-libjpeg#23]

**Comment by SimonBiggs** [comment]
Is it possible to make the wheels just be py3 wheels so that you don't have to keep bumping them?

**Comment by scaramallion** [comment]
I'm not completely sure, but the [docs for cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip) seem to indicate that I can only build against specific versions. I'll have to test it and see.

**Comment by SimonBiggs** [comment]
Fixed in https://github.com/pydicom/pylibjpeg-libjpeg/pull/24

**Comment by SimonBiggs** [comment]
I really appreciate you uploading the source file also:

https://files.pythonhosted.org/packages/a1/46/644cc95d11ad222c79ab8bc1053552ce5b55e99ddb66799752c10f1d3ab7/pylibjpeg-libjpeg-1.2.0.tar.gz

That way, if a new Python version comes out, at least people can attempt to build from source.

**Comment by scaramallion** [comment]
Yeah, I only just realised it was missing
