### ISSUE TITLE
Getting Greeninsh Images from DICOM file 

### ISSUE THREAD

**Issue by PankajSujyot** [pydicom/pylibjpeg-libjpeg#29]
@PankajSujyot please don't post images which have patient identifying information in them

I am getting this kind of result 
but actual result is like this
![image](https://user-images.githubusercontent.com/85339126/120771546-f12e8700-c53c-11eb-8d8c-1080d0e9b569.png)
my code is as follows

ds = pydicom.dcmread(os.path.join(source_folder,file))
plt.imsave(os.path.join(output_folder,file)+'.png',  ds.pixel_array)

TransferSyntax is 1.2.840.10008.1.2.4.70

**Comment by PankajSujyot** [comment]
@scaramallion can you give me example of  Pillow or GDCM
means how to use it

**Comment by scaramallion** [comment]
You just need to [install either](https://pydicom.github.io/pydicom/stable/tutorials/installation.html#installing-pillow) then call `ds.pixel_array` as normal.

**Comment by PankajSujyot** [comment]
@scaramallion  got same result with follwoing code
plt.imsave(os.path.join(output_folder,file)+'.png',  ds.pixel_array)

**Comment by scaramallion** [comment]
The problem with the pylibjpeg handler is that the *Photometric Interpretation* in the dataset is wrong, it should be:
```python
ds.PhotometricInterpretation = "YBR_FULL"
arr = ds.pixel_array
```
The pillow and GDCM handlers ignore the PI and just assume JPEG data is in YBR colour space so they decode correctly.

**Comment by ucs198604** [comment]
Learned so much! Thank you.
Do you know why and how the PI tag information goes wrong and how do we detect or avoid this problem?

**Comment by PankajSujyot** [comment]
@scaramallion 
how to overcome this problem?

**Comment by PankajSujyot** [comment]
@scaramallion Thank you so much
Problem is solved 
I got required result by adding this issue

![image](https://user-images.githubusercontent.com/85339126/121187282-84d9bd80-c885-11eb-8c2a-aa5a6b1a32e7.png)

**Comment by PankajSujyot** [comment]
@scaramallion thanks again for such good information

**Comment by scaramallion** [comment]
No problem!

**Comment by ucs198604** [comment]
Thank you!
