### ISSUE TITLE
error while importing libjpeg

### ISSUE THREAD

**Issue by alirezadizaji** [pydicom/pylibjpeg-libjpeg#32]
Hi,
I am importing the library via `from libjpeg import decode`, and I faced the following traceback:
`  File "/home/alireza/anaconda3/lib/python3.8/site-packages/libjpeg/__init__.py", line 4, in <module>
    from .utils import decode, decode_pixel_data, get_parameters
  File "/home/alireza/anaconda3/lib/python3.8/site-packages/libjpeg/utils.py", line 8, in <module>
    import _libjpeg
  File "libjpeg/_libjpeg.pyx", line 1, in init _libjpeg
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by scaramallion** [comment]
Could you try updating your versions of `pip` and `numpy` please?

**Comment by alirezadizaji** [comment]
yeah it's resolved, thanks
