### ISSUE TITLE
Decompression failure with lossless huffman

### ISSUE THREAD

**Issue by alirezadizaji** [pydicom/pylibjpeg-libjpeg#33]
I have used the following code:
```python
from libjpeg import decode

with open(img_path, 'rb') as f:
    data = f.read()
    img = decode(data)`
```
the input data comes from [this link](http://www.eng.usf.edu/cvprg/Mammography/DDSM/thumbnails/cancers/cancer_08/case1465/A-1465-1.html) (RIGHT_MLO), the saved image is as [this link](https://drive.google.com/file/d/1Uq9yD6LL85j3D88yR-sgjbEtc8F5FYJR/view?usp=sharing)

**Comment by scaramallion** [comment]
Do you have a link to the actual JPEG file? Or is it a DICOM dataset?

**Comment by alirezadizaji** [comment]
I have shared it [here](https://drive.google.com/file/d/1doLyGXNqF-6BKrxuctqthw8QyDB8IUAw/view?usp=sharing)

**Comment by scaramallion** [comment]
```
=================== SOI marker at offset 0 ====================

------------- SOF3 marker at offset 2, length 13 --------------
Lossless (sequential), Huffman coding
Sample size (px): 5491 x 2776
Sample precision (bits): 16
Number of component images: 1
  Component ID: 1
    Horizontal sampling factor: 1
    Vertical sampling factor: 1
    Quantization table destination: 0

------------- DHT marker at offset 15, length 36 --------------
Lossless/DC Huffman, table ID: 0
   1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16
  00 02 02 02 02 03 01 01 01 01 00 00 00 00 00 00 : # codes
  06 07                                           : L = 2
  05 08                                           : L = 3
  00 04                                           : L = 4
  03 09                                           : L = 5
  01 02 0b                                        : L = 6
  0a                                              : L = 7
  0c                                              : L = 8
  0e                                              : L = 9
  0f                                              : L = 10

------------- SOS marker at offset 51, length 10 --------------
Number of image components: 1
  Component: 1, DC table: 0, AC table: 0
Spectral selectors start-end: 7-0
Successive approximation bit high-low: 0-0

................... ENC marker at offset 59....................

16943242 bytes of entropy-coded data
```
It's odd that the rows are 2776 and columns 5491 when the reference image shows the opposite proportions.

**Comment by scaramallion** [comment]
Using the libjpeg's `jpeg` tool directly to decode gives the same output, so either the issue is with the JPEG file or with the upstream libjpeg repo.

**Comment by alirezadizaji** [comment]
could you share the code here?

**Comment by scaramallion** [comment]
[I've created an issue](https://github.com/thorfdbg/libjpeg/issues/63), let's see what they say

**Comment by scaramallion** [comment]
It looks like the answer is that it's a non-conformant JPEG.

**Comment by alirezadizaji** [comment]
Ok, thanks

**Comment by ValZapod** [comment]
>signals a diagonal predictor, it seems to use no prediction at all. 

It is just that. Who and what produced that file? 

As for rotation maybe there was some kind of exif data? Who knows.
