### ISSUE TITLE
Use JPEG XT

### ISSUE THREAD

**Issue by Kik099** [pydicom/pylibjpeg-libjpeg#36]
Hello and sorry for the bothering. I have checked the readme but still  can't understand how can I use the Decoding JPEG XT on a HDR image. Can you help me with that, or give me a hint?

Thanks, Rodrigo Saraiva

**Comment by scaramallion** [comment]
Does this work?
```python
from libjpeg import decode

arr = decode("path/to/file")
```

**Comment by scaramallion** [comment]
No, the libjpeg backend will determine the correct JPEG type by the codestream passed to it by `decode()`.

> And thanks for the help

No problem
