### ISSUE TITLE
New PyPI release required to avoid pip installation failure on Apple M1 device

### ISSUE THREAD

**Issue by jackpaparian** [pydicom/pylibjpeg-libjpeg#39]
When installing on an Apple M1 device, `pip install pylibjpeg-libjpeg==1.3.1` raises the following error: `error: unrecognized command-line option ‘-mfpmath=387’`

A [similar issue](https://github.com/pydicom/pylibjpeg-rle/issues/14) has already been raised in the `pydicom/pylibjpeg-rle` project. I've confirmed that this error is resolved at [master](https://github.com/pydicom/pylibjpeg-libjpeg/commit/2f0864bca2e62b900fada43c235ff4754762bf7e).

Would a project maintainer please push a new release to PyPI? Thanks!

**Comment by SimonBiggs** [comment]
@scaramallion I'd be happy to help maintain this project if need be

**Comment by mrbean-bremen** [comment]
@scaramallion has been absent for quite some time now - I will go ahead and try to make a release.

**Comment by mrbean-bremen** [comment]
Ok, release 1.3.2 is published.

**Comment by SimonBiggs** [comment]
> has been absent for quite some time now

Are they okay?

**Comment by mrbean-bremen** [comment]
> Are they okay?

I haven't heard anything, I hope they are just busy

**Comment by jackpaparian** [comment]
@mrbean-bremen Thanks for publishing the new release!

I just tried running `pip install pylibjpeg-libjpeg==1.3.2`, and I'm still getting `aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-mfpmath=387`.

I confirmed that I can still successfully build from source by cloning the repo and running `python setup.py install`. Does version 1.3.2 on PyPI definitely include the last two commits (`2f0864b` and `692da5e`)?

**Comment by mrbean-bremen** [comment]
The only changes from these commits are a newer version of the libjpeg submodule (2f0864b) and the new version number 1.3.2 (692da5e). The second commit is definitely in, the first one is less obvious, as I have to compare against pylibjpeg - will do that in a moment.

**Comment by mrbean-bremen** [comment]
The source package is definitely updated.

**Comment by thefiddler** [comment]
I have also encountered the "unrecognized command-line option ‘-mfpmath=387’" issue when installing "pylibjpeg-libjpeg==1.3.2" on a native M1 environment.

As the poster above, install from source resolves this issue. Below is my workaround in case someone else encounters this in the future:
```bash
mkdir -p /tmp/pylibjpeg-libjpeg
cd /tmp/pylibjpeg-libjpeg
git clone https://github.com/pydicom/pylibjpeg-libjpeg.git .
git checkout 692da5e44ca4eb2a75d69fc6fd33aaca7f2c7921  # v1.3.2 tag as of the time of this writing
git submodule update --init --recursive
python3 setup.py build
python3 setup.py install
```

I suspect the lies somewhere in the build scripts.

**Comment by jackpaparian** [comment]
I no longer get this issue on M1s or M2s when installing `pylibjpeg-libjpeg==1.3.4`. Thanks for your help!
