### ISSUE TITLE
64-bit ARM Linux wheels

### ISSUE THREAD

**Issue by taleinat** [pydicom/pylibjpeg-libjpeg#42]
Would it be possible to provide binary wheels for 64-bit ARM (a.k.a. "aarch64") Linux?

I see that such wheels are already provided for 64-bit ARM macOS and x86-64 Linux, so hopefully not too difficult to do...

**Comment by mrbean-bremen** [comment]
I don't have experience in that area, but there seems to be [no linux arm64 runner](https://github.com/actions/runner-images/issues/5631) in GH actions yet, so it can't just be added to the build matrix.
There is [an action](https://github.com/uraimo/run-on-arch-action) that gives the possibility to run arm64 on an emulated system that may be used for this, as far as I understand. 
I may have a closer look at this over the weekend, though I would prefer if somebody with access to arm64 linux would try this.

**Comment by taleinat** [comment]
`python-gdcm` recently implemented this, perhaps a similar method can be used? Here is [the relevant commit](https://github.com/tfmoraes/python-gdcm/commit/9fbdae92685ce2333348de10071f4d7e76582eed).

**Comment by mrbean-bremen** [comment]
Thanks - that looks quite helpful! I will probably try this later today.

**Comment by mrbean-bremen** [comment]
I made a new patch release with the aarch64 wheels - please check if these work for you.

**Comment by mrbean-bremen** [comment]
While I added this I noticed that there are still manylinux-2010 wheels are created both in this project and in `pylibjpeg-openjpeg`. As far as I understand, they are no longer needed as all target platforms are unsupported and can be removed. Is there anything I'm missing here?

**Comment by mrbean-bremen** [comment]
Closing this also as done, please reopen if there are problems.

**Comment by taleinat** [comment]
Many thanks @mrbean-bremen! I hope to test these later this week.
