### ISSUE TITLE
v2.02 is typo of v2.0.2?

### ISSUE THREAD

**Issue by hubutui** [pydicom/pylibjpeg-libjpeg#69]
`vercmp 2.02 2.1.0` outputs `1`, which means vercmp recognizes 2.02 > 2.1.0. vercmp is a tool for compare package version numbers using pacman's version comparison logic. pacman is the package manager for ArchLinux. I create package for ArchLinux, but now it says pylibjpeg-libjpeg 2.1.0 is newer than pylibjpeg-libjpeg 2.0.2.

**Comment by scaramallion** [comment]
Oh whoops! Sorry, fixed I think.
